import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Hello world",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: // dashboard
Readonly<{
  children: React.ReactNode;
  dashboard : React.ReactNode;
}>) {
  const isAdmin = false;
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex items-center justify-between p-2 bg-blue-600 text-white">
          <Link href={'/'} className="text-3xl font-bold">BLOGGY</Link>
            <Link className="p-2 text-blue-600 bg-white rounded-md font-medium text-sm" href={"/create"}>Create</Link>
        </nav>
        <div className="px-2 ">{children}</div>
        {/* {isAdmin ? dashboard : ''} */}
      </body>
    </html>
  );
}
